---
title: "DS 3001 Final Project"
author: "Jess Laudie"
date: "12/1/2021"
output:
    html_document:
    toc: TRUE
    theme: journal
    toc_float: TRUE
theme: readable
---


## Using 3 Clusters
```{r, echo=FALSE}
clust_data = audio_features[,c(2:13)]
set.seed(1)
three_kmeans = kmeans(clust_data,centers=3,algorithm="Lloyd")
cluster_audio = as.factor(three_kmeans$cluster)
audio_features$cluster <- three_kmeans$cluster

ggplot(audio_features, aes(x=valence,
                           y=energy,
                           color=Album,
                           shape=cluster_audio))+
  
 geom_point(size = 4) +
  ggtitle("Valence vs. Energy of Taylor Swift Albums") +
  xlab("valence") +
  ylab("energy") +
  scale_shape_manual(name = "Cluster", 
                     labels = c("Cluster 1", "Cluster 2", "Cluster 3"),
                     values = c("1", "2", "3")) +
  scale_color_manual(name = "Album",         #<- tell R which colors to use and
                     #   which labels to include in the legend
                     labels = c('Taylor Swift','Fearless','SpeakNow','Red',
                                '1989','Reputation','Lover','Folklore','Evermore'),
                     values = c("blue", "pink", "purple","red", "yellow", "black", "green", "gray","brown")) +
  theme_light()

```
```{r}
ggplot(audio_features, aes(x=acoustic,
                           y=energy,
                           color=Album,
                           shape=cluster_audio))+
  
 geom_point(size = 4) +
  ggtitle("Acousticness vs. Energy of Taylor Swift Albums") +
  xlab("acousticness") +
  ylab("energy") +
  scale_shape_manual(name = "Cluster", 
                     labels = c("Cluster 1", "Cluster 2", "Cluster 3"),
                     values = c("1", "2", "3")) +
  scale_color_manual(name = "Album",         #<- tell R which colors to use and
                     #   which labels to include in the legend
                     labels = c('Taylor Swift','Fearless','SpeakNow','Red',
                                '1989','Reputation','Lover','Folklore','Evermore'),
                     values = c("blue", "pink", "purple","red", "yellow", "black", "green", "gray","brown")) +
  theme_light()
```


```{R, echo=FALSE, fig.align='center'}
grouped <- audio_features %>%
 group_by(cluster) %>%
 summarise_if(is.numeric, mean)

grouped <- as.matrix(grouped)

color = brewer.pal(3, name = "Blues")

#evaluating characteristics of each cluster
statistics <- barplot(grouped[,c(2:8)],
        beside = TRUE,
        col = color,
        legend.text = grouped[,1])

```

```{R, echo=FALSE, fig.align='center'}
#evaluating characteristics of each cluster
statistics <- barplot(grouped[,c(9:14)],
        beside = TRUE,
        col = color,
        legend.text = grouped[,1])
```
## Using 9 Clusters
```{r, echo=FALSE}
clust_data = audio_features[,c(2:13)]
set.seed(1)
nine_kmeans = kmeans(clust_data,centers=9,algorithm="Lloyd")
cluster_audio = as.factor(nine_kmeans$cluster)
audio_features2<- audio_features
audio_features2$cluster <- nine_kmeans$cluster

ggplot(audio_features, aes(x=valence,
                           y=energy,
                           color=Album,
                           shape=cluster_audio))+
  
 geom_point(size = 4) +
  ggtitle("Valence vs. Energy of Taylor Swift Albums") +
  xlab("valence") +
  ylab("energy") +
  scale_shape_manual(name = "Cluster", 
                     labels = c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4", "Cluster 5","Cluster 6", "Cluster 7", "Cluster 8", "Cluster 9"),
                     values = c("1", "2", "3", "4","5","6","7","8","9")) +
  scale_color_manual(name = "Album",         #<- tell R which colors to use and
                     #   which labels to include in the legend
                     labels = c('Taylor Swift','Fearless','SpeakNow','Red',
                                '1989','Reputation','Lover','Folklore','Evermore'),
                     values = c("blue", "pink", "purple","red", "yellow", "black", "green", "gray","brown")) +
  theme_light()

```
```{r, echo=FALSE,fig.align='center'}
 geom_point(size = 4) +
  ggtitle("Acousticness vs. Energy of Taylor Swift Albums") +
  xlab("acousticness") +
  ylab("energy") +
  scale_shape_manual(name = "Cluster", 
                     labels = c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4", "Cluster 5","Cluster 6", "Cluster 7", "Cluster 8", "Cluster 9"),
                     values = c("1", "2", "3", "4","5","6","7","8","9")) +
  scale_color_manual(name = "Album",         #<- tell R which colors to use and
                     #   which labels to include in the legend
                     labels = c('Taylor Swift','Fearless','SpeakNow','Red',
                                '1989','Reputation','Lover','Folklore','Evermore'),
                     values = c("blue", "pink", "purple","red", "yellow", "black", "green", "gray","brown")) +
  theme_light()
```


